# Generated by Django 6.0.3 on 2026-04-10 05:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_rep_user_id_9178ae_idx',
            old_name='reports_rep_user_id_8f8bc7_idx',
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['resolved_at'], name='reports_rep_resolve_23d6a0_idx'),
        ),
    ]
