# Generated by Django 6.0.3 on 2026-04-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_reports_rep_user_id_8f8bc7_idx_reports_rep_user_id_9178ae_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='road_authority',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
