# Generated by Django 6.0.3 on 2026-04-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_road_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='road_authority_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
