# Generated by Django 5.1.15 on 2026-04-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_road_authority_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pothole_severity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
