# Generated by Django 6.0.3 on 2026-04-07 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PotholeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('image_name', models.CharField(blank=True, max_length=255)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inference_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inferencejob',
            index=models.Index(fields=['submitted_by', 'status'], name='ml_inferenc_submitt_6bdfb9_idx'),
        ),
        migrations.AddField(
            model_name='potholereport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pothole_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='potholereport',
            index=models.Index(fields=['user', 'created_at'], name='ml_potholer_user_id_1cc39c_idx'),
        ),
    ]
